# This is only to avoid "no visible binding" notes in package check. Source solution :
	# https://community.rstudio.com/t/how-to-solve-no-visible-binding-for-global-variable-note/28887/3
	# "hideous hack" according to https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when

## quiets concerns of R CMD check re: the .'s that appear in pipelines
if(getRversion() >= "2.15.1")  utils::globalVariables(c(
	"."
	,"dim_type_dep"                # Complete_commut: no visible binding for global variable ‘dim_type_dep’
	,"inc_age"                     # Complete_commut: no visible binding for global variable ‘inc_age’
	,"‘%>%"                        # Complete_commut: no visible global function definition for ‘%>%’
	,"mutate"                      # Complete_commut: no visible global function definition for ‘mutate’
	,"."                           # Complete_commut: no visible binding for global variable ‘.’
	,"select"                      # Complete_commut: no visible global function definition for ‘select’
	,"lx"                          # Complete_commut: no visible binding for global variable ‘lx’
	,"cc_index"                    # Complete_commut: no visible binding for global variable ‘cc_index’
	,"type"                        # Complete_commut: no visible binding for global variable ‘type’
	,"inc"                         # Complete_commut: no visible binding for global variable ‘inc’
	,"dims"                        # Complete_commut: no visible binding for global variable ‘dims’
	,"qx"                          # Complete_commut: no visible binding for global variable ‘qx’
	,"key_names"                   # Complete_commut: no visible binding for global variable ‘key_names’
	,"inc_p1"                      # Complete_commut: no visible binding for global variable ‘inc_p1’
	,"key_xp1"                     # Complete_commut: no visible binding for global variable ‘key_xp1’
	,"."                           # Complete_commut: no visible global function definition for ‘.’
	,"px"                          # Complete_commut: no visible binding for global variable ‘px’
	,"lxp1"                        # Complete_commut: no visible binding for global variable ‘lxp1’
	,"Dx"                          # Complete_commut: no visible binding for global variable ‘Dx’
	,"dx"                          # Complete_commut: no visible binding for global variable ‘dx’
	,"Cx"                          # Complete_commut: no visible binding for global variable ‘Cx’
	,"replace_na"                  # Complete_commut: no visible global function definition for ‘replace_na’
	,"a_pp_x"                      # Complete_commut: no visible binding for global variable ‘a_pp_x’
	,"Nx"                          # Complete_commut: no visible binding for global variable ‘Nx’
	,"Ax"                          # Complete_commut: no visible binding for global variable ‘Ax’
	,"Mx"                          # Complete_commut: no visible binding for global variable ‘Mx’
	,"ax"                          # Complete_commut: no visible binding for global variable ‘ax’
	,"arrange"                     # Complete_commut: no visible global function definition for ‘arrange’
	,"heure_seconds"               # Complete_commut: no visible binding for global variable ‘heure_seconds’
	,"endOf"                       # Complete_commut: no visible binding for global variable ‘endOf’
	,"dt_seconds"                  # Complete_commut: no visible binding for global variable ‘dt_seconds’
	,"secsPerMLines"               # Complete_commut: no visible binding for global variable ‘secsPerMLines’
	,"‘%>%"                        # age_dec: no visible global function definition for ‘%>%’
	,"‘%>%"                        # complete_pop: no visible global function definition for ‘%>%’
	,"select"                      # complete_pop: no visible global function definition for ‘select’
	,"all_of"                      # complete_pop: no visible global function definition for ‘all_of’
	,"dim_sexe"                    # complete_pop: no visible binding for global variable ‘dim_sexe’
	,"sexe"                        # complete_pop: no visible binding for global variable ‘sexe’
	,"inc_age"                     # complete_pop: no visible binding for global variable ‘inc_age’
	,"dteNais"                     # complete_pop: no visible binding for global variable ‘dteNais’
	,"dteVision"                   # complete_pop: no visible binding for global variable ‘dteVision’
	,"dim_age_sous"                # complete_pop: no visible binding for global variable ‘dim_age_sous’
	,"dteSouscription"             # complete_pop: no visible binding for global variable ‘dteSouscription’
	,"inc_anc"                     # complete_pop: no visible binding for global variable ‘inc_anc’
	,"ct_active"                   # complete_pop: no visible binding for global variable ‘ct_active’
	,"dim_type_dep"                # complete_pop: no visible binding for global variable ‘dim_type_dep’
	,"died"                        # complete_pop: no visible binding for global variable ‘died’
	,"ctStatus"                    # complete_pop: no visible binding for global variable ‘ctStatus’
	,"‘%>%"                        # dep_table: no visible global function definition for ‘%>%’
	,"select"                      # dep_table: no visible global function definition for ‘select’
	,"tx"                          # dep_table: no visible binding for global variable ‘tx’
	,"qx"                          # dep_table: no visible binding for global variable ‘qx’
	,"Dx"                          # dep_table: no visible binding for global variable ‘Dx’
	,"Nx"                          # dep_table: no visible binding for global variable ‘Nx’
	,"äx"                          # dep_table: no visible binding for global variable ‘äx’
	,"relocate"                    # dep_table: no visible global function definition for ‘relocate’
	,"..age_vis_name"              # dep_table: no visible binding for global variable ‘..age_vis_name’
	,"res_rates"                   # dep_table: no visible binding for global variable ‘res_rates’
	,"mutate"                      # dep_table: no visible global function definition for ‘mutate’
	,"qx_vie"                      # dep_table: no visible binding for global variable ‘qx_vie’
	,"qx_inc"                      # dep_table: no visible binding for global variable ‘qx_inc’
	,"qx_vie_inc"                  # dep_table: no visible binding for global variable ‘qx_vie_inc’
	,"qx_res"                      # dep_table: no visible binding for global variable ‘qx_res’
	,"lx"                          # dep_table: no visible binding for global variable ‘lx’
	,"inc"                         # dep_table: no visible binding for global variable ‘inc’
	,"."                           # dep_table: no visible global function definition for ‘.’
	,"a_pp_x"                      # dep_table: no visible binding for global variable ‘a_pp_x’
	,"Dx_age_vis"                  # dep_table: no visible binding for global variable ‘Dx_age_vis’
	,"Ex_dep"                      # dep_table: no visible binding for global variable ‘Ex_dep’
	,"Dx_pres"                     # dep_table: no visible binding for global variable ‘Dx_pres’
	,"VAP_dep"                     # dep_table: no visible binding for global variable ‘VAP_dep’
	,"p_dep"                       # dep_table: no visible binding for global variable ‘p_dep’
	,"a_pp_x_dep"                  # dep_table: no visible binding for global variable ‘a_pp_x_dep’
	,"dim_age_dep"                 # dep_table: no visible binding for global variable ‘dim_age_dep’
	,"."                           # dep_table: no visible binding for global variable ‘.’
	,"group_by"                    # dep_table: no visible global function definition for ‘group_by’
	,"step"                        # dep_table: no visible binding for global variable ‘step’
	,"dt_seconds"                  # dep_table: no visible binding for global variable ‘dt_seconds’
	,"‘%>%"                        # dimsCol: no visible global function definition for ‘%>%’
	,"dimsCols_index"              # dimsCol: no visible binding for global variable ‘dimsCols_index’
	,"dims"                        # dimsCol: no visible binding for global variable ‘dims’
	,"arrange"                     # dimsCol: no visible global function definition for ‘arrange’
	,"heure_seconds"               # dimsCol: no visible binding for global variable ‘heure_seconds’
	,"mutate"                      # dimsCol: no visible global function definition for ‘mutate’
	,"endOf"                       # dimsCol: no visible binding for global variable ‘endOf’
	,"dt_seconds"                  # dimsCol: no visible binding for global variable ‘dt_seconds’
	,"secsPerMLines"               # dimsCol: no visible binding for global variable ‘secsPerMLines’
	,"dim_type_dep"                # extendLifeTable: no visible binding for global variable ‘dim_type_dep’
	,"inc_age"                     # extendLifeTable: no visible binding for global variable ‘inc_age’
	,"tmpInc"                      # extendLifeTable: no visible binding for global variable ‘tmpInc’
	,"tmpDims"                     # extendLifeTable: no visible binding for global variable ‘tmpDims’
	,"‘%>%"                        # extendLifeTable: no visible global function definition for ‘%>%’
	,"arrange"                     # extendLifeTable: no visible global function definition for ‘arrange’
	,"mutate"                      # extendLifeTable: no visible global function definition for ‘mutate’
	,"qx"                          # extendLifeTable: no visible binding for global variable ‘qx’
	,"lag"                         # extendLifeTable: no visible global function definition for ‘lag’
	,"cst"                         # extendLifeTable: no visible binding for global variable ‘cst’
	,"incAdd"                      # extendLifeTable: no visible binding for global variable ‘incAdd’
	,"select"                      # extendLifeTable: no visible global function definition for ‘select’
	,"group_by"                    # extendLifeTable: no visible global function definition for ‘group_by’
	,"filter"                      # extendLifeTable: no visible global function definition for ‘filter’
	,"n"                           # extendLifeTable: no visible global function definition for ‘n’
	,"ungroup"                     # extendLifeTable: no visible binding for global variable ‘ungroup’
	,"nbNA"                        # extendLifeTable: no visible binding for global variable ‘nbNA’
	,"lx"                          # extendLifeTable: no visible binding for global variable ‘lx’
	,"tmpVal"                      # extendLifeTable: no visible binding for global variable ‘tmpVal’
	,"summarise"                   # extendLifeTable: no visible global function definition for ‘summarise’
	,"tmpLxRatio"                  # extendLifeTable: no visible binding for global variable ‘tmpLxRatio’
	,"tmpLxR_propag"               # extendLifeTable: no visible binding for global variable ‘tmpLxR_propag’
	,"tmpVal_cor"                  # extendLifeTable: no visible binding for global variable ‘tmpVal_cor’
	,"all_of"                      # extendLifeTable: no visible global function definition for ‘all_of’
	,"‘%>%"                        # generate_pop: no visible global function definition for ‘%>%’
	,"age_vision"                  # generate_pop: no visible binding for global variable ‘age_vision’
	,"ageDays"                     # generate_pop: no visible binding for global variable ‘ageDays’
	,"dteNais"                     # generate_pop: no visible binding for global variable ‘dteNais’
	,"dteSouscription"             # generate_pop: no visible binding for global variable ‘dteSouscription’
	,"..var_pop"                   # generate_pop: no visible binding for global variable ‘..var_pop’
	,"slice"                       # generate_pop: no visible global function definition for ‘slice’
	,"dteVision_dec"               # generate_pop_old: no visible binding for global variable ‘dteVision_dec’
	,"sexe"                        # generate_pop_old: no visible binding for global variable ‘sexe’
	,"age_vision"                  # generate_pop_old: no visible binding for global variable ‘age_vision’
	,"dteNais_dec"                 # generate_pop_old: no visible binding for global variable ‘dteNais_dec’
	,"dteNais"                     # generate_pop_old: no visible binding for global variable ‘dteNais’
	,"dteSouscription"             # generate_pop_old: no visible binding for global variable ‘dteSouscription’
	,"..var_pop"                   # generate_pop_old: no visible binding for global variable ‘..var_pop’
	,"‘%>%"                        # get_commut_vars: no visible global function definition for ‘%>%’
	,"..variables_table_commut"    # get_commut_vars: no visible binding for global variable ‘..variables_table_commut’
	,"popIndex"                    # get_commut_vars: no visible binding for global variable ‘popIndex’
	,"select"                      # get_commut_vars: no visible global function definition for ‘select’
	,"gc_key"                      # get_commut_vars: no visible binding for global variable ‘gc_key’
	,"arrange"                     # get_commut_vars: no visible global function definition for ‘arrange’
	,"heure_seconds"               # get_commut_vars: no visible binding for global variable ‘heure_seconds’
	,"mutate"                      # get_commut_vars: no visible global function definition for ‘mutate’
	,"endOf"                       # get_commut_vars: no visible binding for global variable ‘endOf’
	,"dt_seconds"                  # get_commut_vars: no visible binding for global variable ‘dt_seconds’
	,"secsPerMLines"               # get_commut_vars: no visible binding for global variable ‘secsPerMLines’
	,"."                           # groupIncsV2: no visible global function definition for ‘.’
	,"val_lx"                      # groupIncsV2: no visible binding for global variable ‘val_lx’
	,"res_rate"                    # groupIncsV2: no visible binding for global variable ‘res_rate’
	,"cst"                         # groupIncsV2: no visible binding for global variable ‘cst’
	,"str_remove_all"              # groupIncsV2: no visible global function definition for ‘str_remove_all’
	,"‘%>%"                        # inc_pop: no visible global function definition for ‘%>%’
	,"ct_active"                   # inc_pop: no visible binding for global variable ‘ct_active’
	,"is_dep"                      # inc_pop: no visible binding for global variable ‘is_dep’
	,"dteVision"                   # inc_pop: no visible binding for global variable ‘dteVision’
	,"mutate"                      # inc_pop: no visible global function definition for ‘mutate’
	,"died"                        # inc_pop: no visible binding for global variable ‘died’
	,"qx_life"                     # inc_pop: no visible binding for global variable ‘qx_life’
	,"turn_dep"                    # inc_pop: no visible binding for global variable ‘turn_dep’
	,"qx_inc"                      # inc_pop: no visible binding for global variable ‘qx_inc’
	,"filter"                      # inc_pop: no visible global function definition for ‘filter’
	,"n"                           # inc_pop: no visible global function definition for ‘n’
	,"dteNais"                     # inc_pop: no visible binding for global variable ‘dteNais’
	,"dteDep"                      # inc_pop: no visible binding for global variable ‘dteDep’
	,"slice_min"                   # inc_pop: no visible global function definition for ‘slice_min’
	,"dim_age_dep"                 # inc_pop: no visible binding for global variable ‘dim_age_dep’
	,"left_join"                   # inc_pop: no visible global function definition for ‘left_join’
	,"tmpAgeRem"                   # inc_pop: no visible binding for global variable ‘tmpAgeRem’
	,"select"                      # inc_pop: no visible global function definition for ‘select’
	,"tmp"                         # inc_pop: no visible binding for global variable ‘tmp’
	,"bind_rows"                   # inc_pop: no visible global function definition for ‘bind_rows’
	,"matches"                     # inc_pop: no visible global function definition for ‘matches’
	,"died_dep"                    # inc_pop: no visible binding for global variable ‘died_dep’
	,"qx_maint"                    # inc_pop: no visible binding for global variable ‘qx_maint’
	,"anti_join"                   # inc_pop: no visible global function definition for ‘anti_join’
	,"mutate_at"                   # inc_pop: no visible global function definition for ‘mutate_at’
	,"all_of"                      # inc_pop: no visible global function definition for ‘all_of’
	,"ctStatus"                    # inc_pop: no visible binding for global variable ‘ctStatus’
	,"case_when"                   # inc_pop: no visible global function definition for ‘case_when’
	,"count"                       # inc_pop: no visible global function definition for ‘count’
	,"ct_prem"                     # inc_pop: no visible binding for global variable ‘ct_prem’
	,"starts_with"                 # inc_pop: no visible global function definition for ‘starts_with’
	,"qx"                          # mergeLifeTables: no visible binding for global variable ‘qx’
	,"res_rate"                    # mergeLifeTables: no visible binding for global variable ‘res_rate’
	,"‘%>%"                        # mergeLifeTables: no visible global function definition for ‘%>%’
	,"testMax"                     # mergeLifeTables: no visible binding for global variable ‘testMax’
	,"intersectLength"             # mergeLifeTables: no visible binding for global variable ‘intersectLength’
	,"Xlength"                     # mergeLifeTables: no visible binding for global variable ‘Xlength’
	,"Ylength"                     # mergeLifeTables: no visible binding for global variable ‘Ylength’
	,"varName"                     # mergeLifeTables: no visible binding for global variable ‘varName’
	,"cst"                         # mergeLifeTables: no visible binding for global variable ‘cst’
	,"VAP_garantie_dep"            # plotPRCRes: no visible binding for global variable ‘VAP_garantie_dep’
	,"quantile"                    # plotPRCRes: no visible global function definition for ‘quantile’
	,"."                           # plotPRCRes: no visible global function definition for ‘.’
	,"nb_lines"                    # plotPRCRes: no visible binding for global variable ‘nb_lines’
	,"‘%>%"                        # qx_to_lx: no visible global function definition for ‘%>%’
	,"m_pres"                      # qx_to_lx: no visible binding for global variable ‘m_pres’
	,"age_vis_name"                # qx_to_lx: no visible binding for global variable ‘age_vis_name’
	,"retain_order"                # qx_to_lx: no visible binding for global variable ‘retain_order’
	,"px"                          # qx_to_lx: no visible binding for global variable ‘px’
	,"dims"                        # qx_to_lx: no visible binding for global variable ‘dims’
	,"inc"                         # qx_to_lx: no visible binding for global variable ‘inc’
	,"lxp1"                        # qx_to_lx: no visible binding for global variable ‘lxp1’
	,"."                           # qx_to_lx: no visible global function definition for ‘.’
	,"inc_p1"                      # qx_to_lx: no visible binding for global variable ‘inc_p1’
	,"key_xp1"                     # qx_to_lx: no visible binding for global variable ‘key_xp1’
	,"select"                      # qx_to_lx: no visible global function definition for ‘select’
	,"matches"                     # qx_to_lx: no visible global function definition for ‘matches’
	,"minInc"                      # qx_to_lx: no visible binding for global variable ‘minInc’
	,"lx"                          # qx_to_lx: no visible binding for global variable ‘lx’
))
